twitter-to-kafka-service:
  twitter-keywords: # We will use the following keywords to filter messages coming from twitter
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: "Welcome to tweeter leecher! :)"
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
